# Generated by Django 5.1.2 on 2025-05-16 06:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifimodule', '0010_cameraimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='drawings/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
